### PR TITLE
Add visual regression tests

### PR DESCRIPTION
**Pull request by stramel**
@jacobwgillespie 

I tested this against the feather icon bug that we recently fixed. This is what a failing test would have looked like.
feather-test-js-feather-activity-1-diff

When we are satisfied with the code, I can add the snapshots

### CODE REVIEW

**Comment by stramel** [comment]
Ping @jacobwgillespie

**Comment by jacobwgillespie** [comment]
Nice, thank you so much for this!  Looks good to me, let's add the snapshots. 👍 

BTW, I've added you as a collaborator to this repository - it still requires PRs / approval / passing tests to merge, etc, but if you'd like to commit directly, feel free!

**Comment by stramel** [comment]
Working on fixing build

**Comment by stramel** [comment]
Really close now. I think I need to modify the tests to run in docker for a consistent test result.

**Comment by stramel** [comment]
I'm not sure why it is failing... tried running it in OSX just to confirm and it still failed. https://travis-ci.org/jacobwgillespie/styled-icons/builds/593675249

Will keep at it though.

**Comment by stramel** [comment]
Alright, I _think_ this last build will work. @jacobwgillespie Did you want this to only run on Master, only on PRs, all the time, or some other condition?

**Comment by stramel** [comment]
Going to close this for now until I can figure out why it is failing. It isn't due to the OS AFAICT, nor flaky tests.

**Pull request closed without merging**
