### PR TITLE
Add remix icons

### LINKED ISSUE #971: Icon pack proposal: Remix Icon
- Name: `Remix Icon`
- License: `Apache License 2.0`
- NPM package: [`remixicon`](https://www.npmjs.com/package/remixicon)
- Website (if any):  https://remixicon.com

> Remix Icon is a set of open-source neutral-style system symbols for designers and developers. Unlike a patchwork icon library, 1700+ icons are all elaborately crafted so that they are born with the gene of readability, consistency and perfect pixels. Each icon was designed in "Outlined" and "Filled" styles based on a 24x24 grid. Of course, all the icons are free for both personal and commercial use.

image

### PR DESCRIPTION
**Pull request by stramel**
Resolves #971 

Currently there is an issue with `bookmark-line`/`bookmark-fill` and `book-mark-line`/`book-mark-fill`. The pascal cased names conflict in the OS.

Broke it into 2 packs, `remix-fill` and `remix-line`

image

image

@jacobwgillespie

### CODE REVIEW

**Comment by stramel** [comment]
Ping @jacobwgillespie

**Comment by stramel** [comment]
@jacobwgillespie Any thoughts on how to resolve the issue with book-mark-fill and bookmark-fill?

**Comment by jacobwgillespie** [comment]
> Any thoughts on how to resolve the issue with book-mark-fill and bookmark-fill?

No strong thoughts, but we could special-case this icon pack and icon name to change `book-mark-fill` to `book-with-mark-fill` or `book-with-bookmark-fill`, since that's the difference between those two icons.

**Comment by stramel** [comment]
I added a special-case for `BookMark` to change it to `BookWithMark`. Would like to wait to merge this until after the regression tests are finished merged.

**Comment by stramel** [comment]
Will continue with this for now since regression tests are being a PITA.

**Comment by Betree** [comment]
Thanks @stramel for making this PR happen, and @jacobwgillespie for the review/maintenance!

**Pull request merged**
