### PR TITLE
Add material variants

### LINKED ISSUE #932: Two Tone options for Material Icons
Is there a plan to support custom options for Icons, like `twoTones` colors (primary + secondary)?

### PR DESCRIPTION
**Pull request by jacobwgillespie**
Replaces #949 using the new package layout.

Closes #932

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
Looks like this is going to hit a similar out-of-memory error 😢

**Comment by stramel** [comment]
Yeah, I figured. I will see if there has been any advances on nextjs's side. No one has looked into the issue afaict.

**Comment by stramel** [comment]
Rebased onto master 🤞

**Comment by stramel** [comment]
@jacobwgillespie Looks like this is good to go 👍

**Pull request merged**
