### PR TITLE
Prepare for v10.3.0 release

### LINKED ISSUE #1220: Missing Ionicons outline pack
Guys, the package `@styled-icons/ionicons-outline` isn't available on npm registry. 
Could you add it? Thanks!

### PR DESCRIPTION
**Pull request by jacobwgillespie**
Fixes #1220

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
So it looks like the pre-processing scripts aren't stripping colors from the `ionicons` icons:

Screenshot 2020-03-08 at 16 55 15

---

Will need to fix this before release...

**Comment by stramel** [comment]
Oof.... The preprocessor was already tricky not to break the icons... I can take a bit of a look again

**Comment by jacobwgillespie** [comment]
I started working on a new GitHub / NPM org to hold the processed icon SVGs - https://github.com/svg-icons/svg-icons (@stramel you've been invited there as well).  We can probably simplify the build process considerably here by pre-processing the SVGs, then `styled-icons` can just read from those when building the React components.

**Comment by stramel** [comment]
Sounds good! I will take a look. 👍🏼

**Comment by stramel** [comment]
Still noticing a bunch of issues with coloring of the icons. Probably need to add a colored test to our integration tests.

image
image
image
image
image
image
image
image
image
image
image
image

**Comment by jacobwgillespie** [comment]
Yep, I haven't added color normalization to the @svg-icons yet, so this is expected - I need to modify the rust to do the following:

- if the `fill` attribute isn't set on the `<svg>` element, set it to `currentColor` - not all icons specify this, so they don't inherit color from their surroundings
- optionally "strip colors", replacing any `fill` or `stroke` attribute values with `currentColor` - some of the icons have hard-coded colors

**Comment by jacobwgillespie** [comment]
> Probably need to add a colored test

Also on this point, yes, I'm planning to add `color: red` to the icon styles for the @svg-icons visual regression tests to pick up issues like this.

**Comment by jacobwgillespie** [comment]
It's working! I'll fix the merge conflict, merge, and release. There are new icon updates that this was blocking, but that'll come in the next minor release, I don't want to hold up this publish.

**Pull request merged**
