### PR TITLE
Generate Updated Material Icons

### LINKED ISSUE #730: Update material ui source to a more recent source
Hi,

the materail ui source on github (https://github.com/google/material-design-icons) is 3 years old and doesn't seem to be maintained any more.
Please update to a more recent source like:
https://github.com/cyberalien/google-material-design-icons-updated

Thx!

### LINKED ISSUE #870: [site] reddit icon is black when all others are white
https://styled-icons.js.org/
Screen Shot 2019-06-19 at 12 18 54 PM

### PR DESCRIPTION
**Pull request by stramel**
**Updates:**
- Updates the material design icon source Fixes #730 	

**Fixes:**
- Fixes all digit names (ie. 360)
- Fixes any paths that have `fill` colors on it (non-none values) Fixes #870 
- Handles other sizes than `24px`

@jacobwgillespie PTAL

### CODE REVIEW

**Comment by stramel** [comment]
Ping @jacobwgillespie

**Comment by jacobwgillespie** [comment]
Hey, thanks for this!

**Comment by jacobwgillespie** [comment]
This should be released as v8.4.0 once the CI build completes! 🎉

**Comment by stramel** [comment]
You're welcome! Thanks for taking a look and merging!

**Pull request merged**
